import { Smile, Coffee, CloudRain, Flame, type LucideIcon } from "lucide-react";

export type MoodId = "senang" | "capek" | "sedih" | "marah";

export interface MoodConfig {
  id: MoodId;
  label: string;
  icon: LucideIcon;
  border: string;
  bg: string;
  text: string;
  glow: string;
  messages: string[];
}

export const MOODS: MoodConfig[] = [
  {
    id: "senang",
    label: "Lagi Senang",
    icon: Smile,
    border: "border-green-400/40",
    bg: "bg-green-500/10",
    text: "text-green-700",
    glow: "shadow-[0_0_20px_rgba(74,222,128,0.15)]",
    messages: [
      "Seneng liat kamu seneng. Serius, itu salah satu hal favoritku di dunia.",
      "Nah gitu dong senyum! Cantiknya jadi nambah 10 kali lipat.",
      "Ikutan seneng bacanya. Rayain momen ini pelan-pelan ya, jangan buru-buru.",
      "Semoga rasa bahagia ini nular ke orang-orang di sekitar kamu juga.",
      "Kalau kamu lagi seneng gini, rasanya duniaku ikut cerah.",
      "Simpen energi baik ini ya, buat jaga-jaga kalau besok ada hari berat.",
      "Aku suka banget versi kamu yang lagi kayak gini. Bersinar!",
      "Cerita dong nanti, apa yang bikin kamu seseneng ini?",
      "Hari baik memang pantes kamu dapetin. Kamu udah berjuang banyak.",
      "Jangan lupa foto momen ini, biar bisa diketawain bareng nanti.",
      "Kamu tau nggak? Senyum kamu itu candu. Aku nggak pernah bosen.",
      "Semesta lagi baik sama kamu hari ini. Nikmatin sepuasnya!",
      "Gapapa lebay dikit kalau lagi seneng. Kamu berhak kok.",
      "Momen kayak gini yang bikin semua perjuangan kamu kebayar.",
      "Aku selalu doain kamu bahagia, dan hari ini doaku kekabul.",
      "Traktir diri sendiri sesuatu yang enak ya, kamu pantes dapet reward.",
      "Kebahagiaan kecil hari ini semoga jadi awal kebahagiaan yang lebih besar.",
      "Pengen banget ada di sana sekarang, ikut ketawa bareng kamu.",
      "Kamu kalau lagi seneng tuh lucu banget tau nggak, gemes.",
      "Semoga senyum kamu hari ini awet sampai besok, lusa, dan seterusnya.",
      "Catet tanggalnya: hari di mana kamu bahagia banget. Biar sering-sering keulang.",
      "Bahagia itu emang paling enak dibagi. Makasih udah bagi ke aku.",
      "Hal baik dateng ke orang baik. Kamu buktinya.",
      "Aku bangga liat kamu sampai di titik ini. Beneran.",
      "Kalau bisa, aku pengen bekuin momen ini biar kamu seneng terus.",
      "Dunia butuh lebih banyak senyum kayak punya kamu.",
      "Jangan tanggung-tanggung senengnya. Gas sampai puas!",
      "Kamu lagi glowing banget hari ini, aku bisa ngerasain dari jauh.",
      "Semoga apa pun yang bikin kamu seneng hari ini, sering-sering mampir.",
      "Nanti malem cerita ya, aku pengen denger semua detailnya.",
      "Rasanya pengen ikut lompat-lompat bareng kamu sekarang.",
      "Kebahagiaanmu itu prioritasku. Hari ini misi berhasil!",
      "Inget ya, kamu pantes bahagia. Bukan kadang-kadang, tapi selalu.",
      "Satu senyum kamu bisa benerin mood aku seharian. Beneran deh.",
      "Seneng kamu = seneng aku. Rumusnya sesimpel itu.",
      "Semoga hari ini jadi salah satu hari yang kamu inget terus.",
      "Kamu keliatan lebih ringan hari ini. Aku suka liatnya.",
      "Nikmatin ya sayang, momen kayak gini nggak boleh dilewatin gitu aja.",
      "Aku ikut senyum-senyum sendiri nih mikirin kamu lagi seneng.",
      "Peluk virtual dulu buat yang lagi bahagia! 🤗",
      "Semoga makin banyak alasan buat kamu senyum ke depannya.",
      "Kamu itu sumber energi positif. Jangan lupa isi ulang punyamu juga.",
      "Hari ini punya kamu. Besok juga. Pokoknya semua hari baik punya kamu.",
      "Yang lagi seneng, awas jangan lupa makan saking excited-nya!",
      "Tuhan lagi senyum ke kamu hari ini kayaknya.",
      "Bagi dong resep senengnya, biar aku ikutan juga.",
      "Kamu pantas dapat semua hal baik yang datang hari ini.",
      "Jangan biarin siapa pun ngerusak mood baik kamu hari ini ya.",
      "Aku sayang kamu, apalagi pas kamu lagi bahagia kayak gini.",
      "Semoga bahagianya bukan cuma hari ini, tapi jadi kebiasaan.",
      "Kamu bersinar hari ini. Jangan redup-redup ya!",
      "Aku selalu di tim kamu, apalagi di hari-hari secerah ini.",
    ],
  },
  {
    id: "capek",
    label: "Lagi Capek",
    icon: Coffee,
    border: "border-yellow-400/40",
    bg: "bg-yellow-500/10",
    text: "text-amber-700",
    glow: "shadow-[0_0_20px_rgba(250,204,21,0.15)]",
    messages: [
      "Istirahat dulu, gapapa. Semua bisa nunggu sebentar kok.",
      "Kamu udah kerja keras banget hari ini. Aku liat itu, walau orang lain nggak.",
      "Minum air putih dulu, tarik napas. Pelan-pelan aja.",
      "Capek itu bukti kamu udah berusaha. Tapi jangan lupa berhenti juga ya.",
      "Nggak semua hal harus selesai hari ini. Sisanya buat besok aja.",
      "Rebahan dulu 10 menit. Itu perintah, bukan saran. 😤",
      "Kamu manusia, bukan mesin. Wajar banget kalau capek.",
      "Kalau bisa, aku pengen jadi bantal kamu sekarang.",
      "Udah makan belum? Jangan sampai capek ditambah laper ya.",
      "Pundakku selalu kosong buat kamu, kapan pun butuh sandaran.",
      "Hari berat nggak akan selamanya. Kamu udah sering buktiin itu.",
      "Matiin notif bentar, dunia nggak akan runtuh kok.",
      "Kamu boleh lambat, yang penting nggak berhenti. Tapi sekarang, istirahat dulu.",
      "Capeknya kamu hari ini, semoga kebayar tidur nyenyak nanti malem.",
      "Jangan keras-keras banget sama diri sendiri ya sayang.",
      "Mandi air anget, terus tidur. Besok kita mulai lagi bareng-bareng.",
      "Aku bangga sama kamu yang tetap jalan walau capek.",
      "Sini aku pijitin... sayangnya dari jauh dulu. Tapi niatnya sampai kok!",
      "Kerjaan boleh numpuk, tapi kesehatan kamu tetap nomor satu.",
      "Kamu nggak harus kuat terus. Kadang capek ya tinggal bilang capek.",
      "Semoga malam ini tidurmu pules banget, tanpa mimpi soal kerjaan.",
      "Satu langkah kecil hari ini tetap langkah. Kamu nggak diem di tempat.",
      "Besok kalau masih berat, ingat ada aku yang selalu dukung kamu.",
      "Jajan yang manis-manis dulu gih, kamu pantes dapet itu.",
      "Kalau hari ini cuma bisa bertahan, itu juga udah prestasi.",
      "Tutup laptopnya. Serius. Sekarang. 😌",
      "Badan kamu udah kasih kode buat istirahat. Dengerin ya.",
      "Nggak apa-apa nolak ajakan orang kalau energimu udah habis.",
      "Kamu udah ngelakuin yang terbaik dengan tenaga yang ada. Itu cukup.",
      "Capek fisik obatnya tidur. Capek hati obatnya... aku? Hehe.",
      "Pelan-pelan ya. Kamu nggak sedang balapan sama siapa pun.",
      "Aku titip peluk buat kamu yang hari ini luar biasa tangguh.",
      "Recharge dulu. HP aja di-charge tiap hari, masa kamu nggak.",
      "Kamu berhak istirahat tanpa ngerasa bersalah.",
      "Semoga besok bangun-bangun badanmu udah enteng lagi.",
      "Yang penting hari ini selesai. Nggak harus sempurna.",
      "Jangan lupa regangin badan, udah duduk berapa jam coba?",
      "Kalau semuanya kerasa berat, angkat satu-satu. Jangan semua sekaligus.",
      "Aku di sini kalau kamu cuma pengen diem tanpa ngomong apa-apa.",
      "Kamu boleh kok bilang 'nggak dulu' ke hal-hal yang nguras tenaga.",
      "Hari ini berat? Berarti kamu lagi naik level. Tapi save dulu, istirahat.",
      "Tarik napas 4 detik, tahan 4 detik, buang 4 detik. Ulang 3 kali ya.",
      "Kamu udah jadi orang hebat hari ini. Sekarang jadi orang tidur ya.",
      "Semangatmu boleh habis hari ini, stokku masih banyak. Ambil punyaku.",
      "Nggak usah mikirin besok dulu. Malam ini fokus istirahat aja.",
      "Aku sayang kamu di hari produktifmu, dan lebih sayang di hari capekmu.",
      "Kasur udah manggil-manggil tuh. Jangan PHP-in dia.",
      "Kamu udah nampung banyak hal hari ini. Sekarang taruh dulu semuanya.",
      "Capek itu sementara. Bangganya aku ke kamu yang permanen.",
      "Semoga secangkir minuman hangat bisa benerin sisa harimu.",
      "Tubuhmu udah nemenin kamu seharian. Balas dia dengan istirahat.",
      "Besok masih ada. Kamu nggak harus jadi segalanya malam ini.",
    ],
  },
  {
    id: "sedih",
    label: "Lagi Sedih",
    icon: CloudRain,
    border: "border-orange-400/40",
    bg: "bg-orange-500/10",
    text: "text-orange-700",
    glow: "shadow-[0_0_20px_rgba(251,146,60,0.15)]",
    messages: [
      "Gapapa nangis dulu. Aku di sini, nggak ke mana-mana.",
      "Sedih itu wajar. Kamu nggak harus pura-pura kuat di depanku.",
      "Kamu nggak sendirian ngerasain ini. Ada aku, selalu.",
      "Perasaanmu valid. Jangan biarin siapa pun bilang kamu lebay.",
      "Hujan di hati nggak selamanya. Nanti terang lagi, aku janji nemenin sampai reda.",
      "Peluk dulu yang erat. Nggak usah cerita kalau belum siap.",
      "Hal yang bikin kamu sedih hari ini, nggak ngurangin betapa berharganya kamu.",
      "Nangis bukan tanda lemah. Itu tanda kamu udah nahan terlalu lama.",
      "Aku nggak bisa janji semua langsung baik, tapi aku bisa janji nggak ninggalin.",
      "Kalau dunia lagi jahat, ingat ada satu orang yang selalu di pihakmu: aku.",
      "Pelan-pelan aja ngelewatinnya. Nggak ada deadline buat pulih.",
      "Kamu pernah ngelewatin hari yang lebih berat dari ini, dan kamu selamat.",
      "Sedihmu aku temenin. Nanti senyummu juga aku temenin.",
      "Nggak usah jawab 'aku gapapa' kalau sebenarnya nggak. Ke aku boleh jujur.",
      "Hari ini boleh jadi hari yang buruk, tapi kamu bukan orang yang buruk.",
      "Aku sayang kamu. Di versi terbaikmu, dan di versi hari ini juga.",
      "Cerita yuk, atau diem bareng juga boleh. Aku ikut aja maunya kamu.",
      "Jangan lupa makan walau lagi sedih ya. Hatimu butuh tenaga buat sembuh.",
      "Besok mungkin belum baik-baik aja, tapi pasti lebih ringan dari hari ini.",
      "Kamu berhak ngerasain semua emosi itu. Nggak usah buru-buru baik-baik aja.",
      "Aku bangga kamu masih bertahan sampai detik ini.",
      "Yang kamu rasain sekarang berat, dan kamu tetap jalan. Itu luar biasa.",
      "Semoga tidurmu malam ini jadi jeda yang menenangkan.",
      "Sedih boleh mampir, tapi jangan kasih dia kunci rumah ya.",
      "Aku nggak akan nyuruh kamu semangat. Aku cuma mau nemenin dulu.",
      "Kalau air mata udah habis, ada aku yang siap dengerin sisanya.",
      "Satu hari yang buruk nggak menghapus semua hari baik yang nunggu kamu.",
      "Nggak apa-apa merasa hancur dulu. Nanti kita rakit lagi bareng-bareng.",
      "Kamu masih orang yang sama yang aku sayang, sedih atau nggak.",
      "Tuhan nggak pernah salah nitipn beban. Kamu lebih kuat dari yang kamu kira.",
      "Boleh sedih, asal jangan lupa: ini bab, bukan keseluruhan cerita.",
      "Aku kirim peluk paling hangat yang aku punya. Terima ya.",
      "Kadang hati butuh hujan dulu biar bisa numbuhin hal baru.",
      "Nggak usah malu udah nangis. Itu artinya kamu peduli sama hidupmu.",
      "Apa pun yang hilang hari ini, kamu nggak akan pernah kehilangan aku.",
      "Duduk dulu, napas dulu. Nggak semua harus diselesain sekarang.",
      "Rasa sakit ini nyata, tapi begitu juga kekuatanmu.",
      "Aku di ujung telepon kapan pun kamu butuh. Jam berapa pun.",
      "Hati yang lagi patah tetap hati yang paling baik yang pernah aku kenal.",
      "Sedihmu nggak ngerepotin aku. Jangan pernah mikir gitu ya.",
      "Semoga ada satu hal kecil hari ini yang bisa bikin kamu senyum tipis.",
      "Aku percaya sama kamu, bahkan saat kamu lagi nggak percaya sama diri sendiri.",
      "Nggak harus kuat sekarang. Kuatnya nanti aja, bareng aku.",
      "Kamu udah sering bangkit. Kali ini juga pasti bisa, pelan-pelan.",
      "Air mata itu bahasa hati yang jujur. Nggak usah ditahan-tahan.",
      "Aku selalu bangga jadi tempat kamu pulang, termasuk hari ini.",
      "Semesta masih nyimpen banyak hal baik buat kamu. Ini belum tamat.",
      "Yang penting hari ini kamu masih di sini. Itu udah cukup.",
      "Sedihmu berat, tapi kita bagi dua ya. Biar kamu bawanya lebih ringan.",
      "Besok aku mau liat kamu lebih baik. Tapi malam ini, istirahat dulu.",
      "Kamu nggak pernah sendirian. Baca ini sekali lagi kalau perlu.",
      "Apa pun yang terjadi, kamu tetap rumah favoritku.",
    ],
  },
  {
    id: "marah",
    label: "Lagi Marah",
    icon: Flame,
    border: "border-red-400/40",
    bg: "bg-red-500/10",
    text: "text-red-700",
    glow: "shadow-[0_0_20px_rgba(248,113,113,0.15)]",
    messages: [
      "Tarik napas dulu, pelan-pelan. Kamu berhak kesel kok.",
      "Boleh marah, tapi jangan lupa sayang sama diri sendiri juga ya.",
      "Aku di sini kalau kamu butuh tempat buat ngeluarin semuanya.",
      "Kesel itu manusiawi. Yang penting jangan sampai nyakitin diri sendiri.",
      "Cerita aja ke aku, mau sambil ngomel juga gapapa. Aku dengerin.",
      "Kamu nggak salah ngerasa marah. Perasaan itu ada alasannya.",
      "Minum dulu, duduk dulu. Jangan bales chat siapa pun dulu. 😤",
      "Orang yang bikin kamu kesel itu nggak pantes dapet energimu segini banyak.",
      "Marah boleh, tapi jangan lama-lama ya. Sayang waktumu.",
      "Aku tim kamu. Siapa yang gangguin kamu, hadapin aku dulu. 😾",
      "Napas 5 detik, buang 5 detik. Ulangi sampai dadanya lebih ringan.",
      "Nggak usah buru-buru maafin. Tapi jangan biarin dendam nginep juga.",
      "Kadang marah itu bahasa lain dari 'aku terluka'. Aku ngerti kok.",
      "Tulis semua unek-unekmu di notes dulu. Jangan langsung dikirim ya!",
      "Kamu terlalu berharga buat dibikin naik darah sama hal begituan.",
      "Emosi boleh panas, keputusan harus tetap dingin. Tunggu redah dulu.",
      "Mau aku bikinin daftar kata-kata kasar yang boleh dipakai? Bercanda. Peluk dulu.",
      "Habis ini kita cari makanan enak yuk, marah bikin laper soalnya.",
      "Kamu berhak membela diri. Tapi pastikan caranya nggak nyakitin kamu balik.",
      "Jangan ambil keputusan besar pas lagi marah ya. Janji?",
      "Aku percaya versi ceritamu. Kamu nggak perlu buktiin apa-apa ke aku.",
      "Kesel sama dunia? Wajar. Dunia kadang emang nyebelin.",
      "Pukul bantal aja dulu, jangan pukul yang lain. 😌",
      "Amarahmu valid, tapi damaimu lebih berharga.",
      "Udah nggak usah dipikirin orangnya. Mereka nggak mikirin kamu segini seriusnya.",
      "Jalan kaki bentar yuk, biar panasnya keluar lewat keringat.",
      "Kamu bukan orang jahat karena marah. Kamu orang baik yang lagi terluka.",
      "Simpen tenagamu buat orang-orang yang pantes, kayak... aku? Hehe.",
      "Besok hal ini mungkin cuma jadi cerita lucu. Tapi hari ini, kesel dulu gapapa.",
      "Aku nggak akan bilang 'jangan marah'. Aku cuma mau nemenin sampai reda.",
      "Keluarin semuanya sekarang, biar nggak jadi racun di dalam.",
      "Hitung mundur dari 10 dulu. Kalau masih kesel, ulang dari 100.",
      "Kamu punya hak penuh buat jaga batasan. Jangan merasa bersalah.",
      "Musuhnya siapa? Sini aku catat namanya. ✍️😤",
      "Semoga keselmu cepet reda dan digantiin hal yang bikin ketawa.",
      "Marah itu api. Jangan biarin dia bakar rumahmu sendiri.",
      "Screenshot dulu, bales nanti kalau kepala udah dingin. Percaya deh.",
      "Aku sayang kamu bahkan pas kamu lagi mode singa gini. 🦁",
      "Yang penting kamu udah jujur sama perasaanmu. Itu langkah pertama.",
      "Nggak semua hal butuh reaksimu. Ada yang cukup ditinggalin aja.",
      "Kamu lebih besar dari masalah ini. Jauh lebih besar.",
      "Mereka nggak tau aja lagi berhadapan sama orang yang aku banggain.",
      "Dengerin lagu yang keras dulu gih, teriak juga boleh.",
      "Hal yang bikin kamu marah nggak akan menang kalau kamu tetap waras.",
      "Aku siap dengerin versi lengkapnya. Dari awal. Nggak usah disingkat.",
      "Tenang bukan berarti kalah. Tenang itu levelnya di atas marah.",
      "Marahmu hari ini jangan sampai nyuri tidurmu malam ini ya.",
      "Kamu udah nahan banyak. Wajar kalau akhirnya meledak. Sekarang, napas.",
      "Apa pun yang terjadi, jangan lupa: kamu nggak sendirian ngadepinnya.",
      "Besok kita mulai lagi dengan kepala dingin. Malam ini, lepasin dulu.",
      "Kalau butuh partner in crime buat julid bentar, aku orangnya. 😏",
      "Redain pelan-pelan ya. Aku tunggu sampai kamu tenang, nggak ke mana-mana.",
    ],
  },
];
